"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = require("tslib");
var react_1 = require("react");
var config_provider_1 = require("../config-provider");
var time_picker_1 = require("./time-picker");
var ConfigTimePicker = config_provider_1.default.config(time_picker_1.default);
ConfigTimePicker.RangePicker = react_1.default.forwardRef(function (props, ref) { return react_1.default.createElement(ConfigTimePicker, tslib_1.__assign({ ref: ref }, props, { type: "range" })); });
ConfigTimePicker.RangePicker.displayName = 'RangePicker';
exports.default = ConfigTimePicker;
