import * as dayjs from 'dayjs';
import * as customParseFormat from 'dayjs/plugin/customParseFormat';
import * as updateLocale from 'dayjs/plugin/updateLocale';
import * as localeData from 'dayjs/plugin/localeData';
import * as quarterOfYear from 'dayjs/plugin/quarterOfYear';
import * as advancedFormat from 'dayjs/plugin/advancedFormat';
import * as weekOfYear from 'dayjs/plugin/weekOfYear';
import 'dayjs/locale/zh-cn';
dayjs.extend(advancedFormat);
dayjs.extend(quarterOfYear);
dayjs.extend(customParseFormat);
dayjs.extend(updateLocale);
dayjs.extend(localeData);
dayjs.extend(weekOfYear);
dayjs.locale('zh-cn');
var datejs = dayjs;
datejs.isSelf = dayjs.isDayjs;
dayjs.localeData();
export default datejs;
