module.exports = {
  'Affix':  {
    demos: [
      '/compiled_docs/affix/demo/absolute-position.en-us.md',
      '/compiled_docs/affix/demo/absolute-position.md',
      '/compiled_docs/affix/demo/basic.en-us.md',
      '/compiled_docs/affix/demo/basic.md',
      '/compiled_docs/affix/demo/custom-container.en-us.md',
      '/compiled_docs/affix/demo/custom-container.md',
      '/compiled_docs/affix/demo/custom-offset.en-us.md',
      '/compiled_docs/affix/demo/custom-offset.md',
      '/compiled_docs/affix/demo/on-affix.en-us.md',
      '/compiled_docs/affix/demo/on-affix.md',
    ],

    readme: [
      '/compiled_docs/affix/index.en-us.md',
      '/compiled_docs/affix/index.md',
    ],
  },
  'Animate':  {
    demos: [
      '/compiled_docs/animate/demo/basic.en-us.md',
      '/compiled_docs/animate/demo/basic.md',
      '/compiled_docs/animate/demo/expand.en-us.md',
      '/compiled_docs/animate/demo/expand.md',
      '/compiled_docs/animate/demo/multiple.en-us.md',
      '/compiled_docs/animate/demo/multiple.md',
    ],

    readme: [
      '/compiled_docs/animate/index.en-us.md',
      '/compiled_docs/animate/index.md',
    ],
  },
  'Avatar':  {
    demos: [
      '/compiled_docs/avatar/demo/basic.en-us.md',
      '/compiled_docs/avatar/demo/basic.md',
      '/compiled_docs/avatar/demo/type.en-us.md',
      '/compiled_docs/avatar/demo/type.md',
      '/compiled_docs/avatar/demo/with-badge.en-us.md',
      '/compiled_docs/avatar/demo/with-badge.md',
    ],

    readme: [
      '/compiled_docs/avatar/index.en-us.md',
      '/compiled_docs/avatar/index.md',
    ],
  },
  'Badge':  {
    demos: [
      '/compiled_docs/badge/demo/basic.en-us.md',
      '/compiled_docs/badge/demo/basic.md',
      '/compiled_docs/badge/demo/change.en-us.md',
      '/compiled_docs/badge/demo/change.md',
      '/compiled_docs/badge/demo/content.en-us.md',
      '/compiled_docs/badge/demo/content.md',
      '/compiled_docs/badge/demo/dot.en-us.md',
      '/compiled_docs/badge/demo/dot.md',
      '/compiled_docs/badge/demo/no-wrapper.en-us.md',
      '/compiled_docs/badge/demo/no-wrapper.md',
      '/compiled_docs/badge/demo/plus.en-us.md',
      '/compiled_docs/badge/demo/plus.md',
    ],

    readme: [
      '/compiled_docs/badge/index.en-us.md',
      '/compiled_docs/badge/index.md',
    ],
  },
  'Balloon':  {
    demos: [
      '/compiled_docs/balloon/demo/accessibility.en-us.md',
      '/compiled_docs/balloon/demo/accessibility.md',
      '/compiled_docs/balloon/demo/alignment.en-us.md',
      '/compiled_docs/balloon/demo/alignment.md',
      '/compiled_docs/balloon/demo/basic.en-us.md',
      '/compiled_docs/balloon/demo/basic.md',
      '/compiled_docs/balloon/demo/control.en-us.md',
      '/compiled_docs/balloon/demo/control.md',
      '/compiled_docs/balloon/demo/nested.en-us.md',
      '/compiled_docs/balloon/demo/nested.md',
      '/compiled_docs/balloon/demo/onCloseClick.en-us.md',
      '/compiled_docs/balloon/demo/onCloseClick.md',
      '/compiled_docs/balloon/demo/tooltip.en-us.md',
      '/compiled_docs/balloon/demo/tooltip.md',
      '/compiled_docs/balloon/demo/triggerType.en-us.md',
      '/compiled_docs/balloon/demo/triggerType.md',
    ],

    readme: [
      '/compiled_docs/balloon/index.en-us.md',
      '/compiled_docs/balloon/index.md',
    ],
  },
  'Box':  {
    demos: [
      '/compiled_docs/box/demo/align&justify.en-us.md',
      '/compiled_docs/box/demo/align&justify.md',
      '/compiled_docs/box/demo/basic.en-us.md',
      '/compiled_docs/box/demo/basic.md',
      '/compiled_docs/box/demo/direction.en-us.md',
      '/compiled_docs/box/demo/direction.md',
      '/compiled_docs/box/demo/padding&margin.en-us.md',
      '/compiled_docs/box/demo/padding&margin.md',
      '/compiled_docs/box/demo/wrap.en-us.md',
      '/compiled_docs/box/demo/wrap.md',
    ],

    readme: [
      '/compiled_docs/box/index.en-us.md',
      '/compiled_docs/box/index.md',
    ],
  },
  'Breadcrumb':  {
    demos: [
      '/compiled_docs/breadcrumb/demo/basic.en-us.md',
      '/compiled_docs/breadcrumb/demo/basic.md',
      '/compiled_docs/breadcrumb/demo/more.en-us.md',
      '/compiled_docs/breadcrumb/demo/more.md',
      '/compiled_docs/breadcrumb/demo/separator.en-us.md',
      '/compiled_docs/breadcrumb/demo/separator.md',
    ],

    readme: [
      '/compiled_docs/breadcrumb/index.en-us.md',
      '/compiled_docs/breadcrumb/index.md',
    ],
  },
  'Button':  {
    demos: [
      '/compiled_docs/button/demo/accessibility.en-us.md',
      '/compiled_docs/button/demo/accessibility.md',
      '/compiled_docs/button/demo/basic.en-us.md',
      '/compiled_docs/button/demo/basic.md',
      '/compiled_docs/button/demo/component.en-us.md',
      '/compiled_docs/button/demo/component.md',
      '/compiled_docs/button/demo/custom-icons.md',
      '/compiled_docs/button/demo/disabled.en-us.md',
      '/compiled_docs/button/demo/disabled.md',
      '/compiled_docs/button/demo/ghost.en-us.md',
      '/compiled_docs/button/demo/ghost.md',
      '/compiled_docs/button/demo/group.en-us.md',
      '/compiled_docs/button/demo/group.md',
      '/compiled_docs/button/demo/icon.en-us.md',
      '/compiled_docs/button/demo/icon.md',
      '/compiled_docs/button/demo/loading.en-us.md',
      '/compiled_docs/button/demo/loading.md',
      '/compiled_docs/button/demo/size.en-us.md',
      '/compiled_docs/button/demo/size.md',
    ],

    readme: [
      '/compiled_docs/button/index.en-us.md',
      '/compiled_docs/button/index.md',
    ],
  },
  'Calendar':  {
    demos: [
      '/compiled_docs/calendar/demo/basic.en-us.md',
      '/compiled_docs/calendar/demo/basic.md',
      '/compiled_docs/calendar/demo/card.en-us.md',
      '/compiled_docs/calendar/demo/card.md',
      '/compiled_docs/calendar/demo/custom-cell.en-us.md',
      '/compiled_docs/calendar/demo/custom-cell.md',
      '/compiled_docs/calendar/demo/default-visible-month.en-us.md',
      '/compiled_docs/calendar/demo/default-visible-month.md',
      '/compiled_docs/calendar/demo/disabled.en-us.md',
      '/compiled_docs/calendar/demo/disabled.md',
      '/compiled_docs/calendar/demo/locale.en-us.md',
      '/compiled_docs/calendar/demo/locale.md',
      '/compiled_docs/calendar/demo/lunar.en-us.md',
      '/compiled_docs/calendar/demo/lunar.md',
      '/compiled_docs/calendar/demo/panel.en-us.md',
      '/compiled_docs/calendar/demo/panel.md',
    ],

    readme: [
      '/compiled_docs/calendar/index.en-us.md',
      '/compiled_docs/calendar/index.md',
    ],
  },
  'Card':  {
    demos: [
      '/compiled_docs/card/demo/basic.en-us.md',
      '/compiled_docs/card/demo/basic.md',
      '/compiled_docs/card/demo/divider.en-us.md',
      '/compiled_docs/card/demo/divider.md',
      '/compiled_docs/card/demo/free.en-us.md',
      '/compiled_docs/card/demo/free.md',
      '/compiled_docs/card/demo/media.en-us.md',
      '/compiled_docs/card/demo/media.md',
    ],

    readme: [
      '/compiled_docs/card/index.en-us.md',
      '/compiled_docs/card/index.md',
    ],
  },
  'Cascader':  {
    demos: [
      '/compiled_docs/cascader/demo/basic.en-us.md',
      '/compiled_docs/cascader/demo/basic.md',
      '/compiled_docs/cascader/demo/custom-style.en-us.md',
      '/compiled_docs/cascader/demo/custom-style.md',
      '/compiled_docs/cascader/demo/dynamic.en-us.md',
      '/compiled_docs/cascader/demo/dynamic.md',
      '/compiled_docs/cascader/demo/expand-trigger.en-us.md',
      '/compiled_docs/cascader/demo/expand-trigger.md',
      '/compiled_docs/cascader/demo/multiple-control.en-us.md',
      '/compiled_docs/cascader/demo/multiple-control.md',
      '/compiled_docs/cascader/demo/multiple.en-us.md',
      '/compiled_docs/cascader/demo/multiple.md',
      '/compiled_docs/cascader/demo/single-control.en-us.md',
      '/compiled_docs/cascader/demo/single-control.md',
      '/compiled_docs/cascader/demo/source.en-us.md',
      '/compiled_docs/cascader/demo/source.md',
    ],

    readme: [
      '/compiled_docs/cascader/index.en-us.md',
      '/compiled_docs/cascader/index.md',
    ],
  },
  'CascaderSelect':  {
    demos: [
      '/compiled_docs/cascader-select/demo/accessibility.en-us.md',
      '/compiled_docs/cascader-select/demo/accessibility.md',
      '/compiled_docs/cascader-select/demo/basic.en-us.md',
      '/compiled_docs/cascader-select/demo/basic.md',
      '/compiled_docs/cascader-select/demo/custom-style.en-us.md',
      '/compiled_docs/cascader-select/demo/custom-style.md',
      '/compiled_docs/cascader-select/demo/custom.md',
      '/compiled_docs/cascader-select/demo/dynamic.en-us.md',
      '/compiled_docs/cascader-select/demo/dynamic.md',
      '/compiled_docs/cascader-select/demo/expand-trigger.en-us.md',
      '/compiled_docs/cascader-select/demo/expand-trigger.md',
      '/compiled_docs/cascader-select/demo/multiple-control.en-us.md',
      '/compiled_docs/cascader-select/demo/multiple-control.md',
      '/compiled_docs/cascader-select/demo/multiple.en-us.md',
      '/compiled_docs/cascader-select/demo/multiple.md',
      '/compiled_docs/cascader-select/demo/search.en-us.md',
      '/compiled_docs/cascader-select/demo/search.md',
      '/compiled_docs/cascader-select/demo/single-control.en-us.md',
      '/compiled_docs/cascader-select/demo/single-control.md',
    ],

    readme: [
      '/compiled_docs/cascader-select/index.en-us.md',
      '/compiled_docs/cascader-select/index.md',
    ],
  },
  'Checkbox':  {
    demos: [
      '/compiled_docs/checkbox/demo/accessibility.en-us.md',
      '/compiled_docs/checkbox/demo/accessibility.md',
      '/compiled_docs/checkbox/demo/basic.en-us.md',
      '/compiled_docs/checkbox/demo/basic.md',
      '/compiled_docs/checkbox/demo/control.en-us.md',
      '/compiled_docs/checkbox/demo/control.md',
      '/compiled_docs/checkbox/demo/group.en-us.md',
      '/compiled_docs/checkbox/demo/group.md',
      '/compiled_docs/checkbox/demo/indeterminate.en-us.md',
      '/compiled_docs/checkbox/demo/indeterminate.md',
      '/compiled_docs/checkbox/demo/nest.en-us.md',
      '/compiled_docs/checkbox/demo/nest.md',
      '/compiled_docs/checkbox/demo/uncontrol.en-us.md',
      '/compiled_docs/checkbox/demo/uncontrol.md',
    ],

    readme: [
      '/compiled_docs/checkbox/index.en-us.md',
      '/compiled_docs/checkbox/index.md',
    ],
  },
  'Collapse':  {
    demos: [
      '/compiled_docs/collapse/demo/accessibility.en-us.md',
      '/compiled_docs/collapse/demo/accessibility.md',
      '/compiled_docs/collapse/demo/accordion.en-us.md',
      '/compiled_docs/collapse/demo/accordion.md',
      '/compiled_docs/collapse/demo/basic.en-us.md',
      '/compiled_docs/collapse/demo/basic.md',
      '/compiled_docs/collapse/demo/datasource.en-us.md',
      '/compiled_docs/collapse/demo/datasource.md',
      '/compiled_docs/collapse/demo/disabled.en-us.md',
      '/compiled_docs/collapse/demo/disabled.md',
      '/compiled_docs/collapse/demo/event.en-us.md',
      '/compiled_docs/collapse/demo/event.md',
      '/compiled_docs/collapse/demo/nested.en-us.md',
      '/compiled_docs/collapse/demo/nested.md',
    ],

    readme: [
      '/compiled_docs/collapse/index.en-us.md',
      '/compiled_docs/collapse/index.md',
    ],
  },
  'ConfigProvider':  {
    demos: [
      '/compiled_docs/config-provider/demo/basic.en-us.md',
      '/compiled_docs/config-provider/demo/basic.md',
      '/compiled_docs/config-provider/demo/components.en-us.md',
      '/compiled_docs/config-provider/demo/components.md',
      '/compiled_docs/config-provider/demo/consumer.en-us.md',
      '/compiled_docs/config-provider/demo/consumer.md',
      '/compiled_docs/config-provider/demo/error-boundary.en-us.md',
      '/compiled_docs/config-provider/demo/error-boundary.md',
      '/compiled_docs/config-provider/demo/locale.en-us.md',
      '/compiled_docs/config-provider/demo/locale.md',
      '/compiled_docs/config-provider/demo/rtl.en-us.md',
      '/compiled_docs/config-provider/demo/rtl.md',
    ],

    readme: [
      '/compiled_docs/config-provider/index.en-us.md',
      '/compiled_docs/config-provider/index.md',
    ],
  },
  'DatePicker':  {
    demos: [
      '/compiled_docs/date-picker/demo/accessibility.en-us.md',
      '/compiled_docs/date-picker/demo/accessibility.md',
      '/compiled_docs/date-picker/demo/basic.en-us.md',
      '/compiled_docs/date-picker/demo/basic.md',
      '/compiled_docs/date-picker/demo/custom-range-picker.en-us.md',
      '/compiled_docs/date-picker/demo/custom-range-picker.md',
      '/compiled_docs/date-picker/demo/default-visible-month.en-us.md',
      '/compiled_docs/date-picker/demo/default-visible-month.md',
      '/compiled_docs/date-picker/demo/default.en-us.md',
      '/compiled_docs/date-picker/demo/default.md',
      '/compiled_docs/date-picker/demo/disabled-date.en-us.md',
      '/compiled_docs/date-picker/demo/disabled-date.md',
      '/compiled_docs/date-picker/demo/disabled.en-us.md',
      '/compiled_docs/date-picker/demo/disabled.md',
      '/compiled_docs/date-picker/demo/field.en-us.md',
      '/compiled_docs/date-picker/demo/field.md',
      '/compiled_docs/date-picker/demo/footer.en-us.md',
      '/compiled_docs/date-picker/demo/footer.md',
      '/compiled_docs/date-picker/demo/format.en-us.md',
      '/compiled_docs/date-picker/demo/format.md',
      '/compiled_docs/date-picker/demo/popup.en-us.md',
      '/compiled_docs/date-picker/demo/popup.md',
      '/compiled_docs/date-picker/demo/show-time.en-us.md',
      '/compiled_docs/date-picker/demo/show-time.md',
      '/compiled_docs/date-picker/demo/size.en-us.md',
      '/compiled_docs/date-picker/demo/size.md',
    ],

    readme: [
      '/compiled_docs/date-picker/index.en-us.md',
      '/compiled_docs/date-picker/index.md',
    ],
  },
  'Dialog':  {
    demos: [
      '/compiled_docs/dialog/demo/accessibility.en-us.md',
      '/compiled_docs/dialog/demo/accessibility.md',
      '/compiled_docs/dialog/demo/basic.en-us.md',
      '/compiled_docs/dialog/demo/basic.md',
      '/compiled_docs/dialog/demo/customize-footer.en-us.md',
      '/compiled_docs/dialog/demo/customize-footer.md',
      '/compiled_docs/dialog/demo/fixed-height.en-us.md',
      '/compiled_docs/dialog/demo/fixed-height.md',
      '/compiled_docs/dialog/demo/footer.en-us.md',
      '/compiled_docs/dialog/demo/footer.md',
      '/compiled_docs/dialog/demo/large-content.en-us.md',
      '/compiled_docs/dialog/demo/large-content.md',
      '/compiled_docs/dialog/demo/promise.en-us.md',
      '/compiled_docs/dialog/demo/promise.md',
      '/compiled_docs/dialog/demo/quick.en-us.md',
      '/compiled_docs/dialog/demo/quick.md',
      '/compiled_docs/dialog/demo/should-update-position.en-us.md',
      '/compiled_docs/dialog/demo/should-update-position.md',
    ],

    readme: [
      '/compiled_docs/dialog/index.en-us.md',
      '/compiled_docs/dialog/index.md',
    ],
  },
  'Divider':  {
    demos: [
      '/compiled_docs/divider/demo/basic.en-us.md',
      '/compiled_docs/divider/demo/basic.md',
      '/compiled_docs/divider/demo/orientation.en-us.md',
      '/compiled_docs/divider/demo/orientation.md',
    ],

    readme: [
      '/compiled_docs/divider/index.en-us.md',
      '/compiled_docs/divider/index.md',
    ],
  },
  'Drawer':  {
    demos: [
      '/compiled_docs/drawer/demo/basic.en-us.md',
      '/compiled_docs/drawer/demo/basic.md',
      '/compiled_docs/drawer/demo/double.en-us.md',
      '/compiled_docs/drawer/demo/double.md',
      '/compiled_docs/drawer/demo/placement.en-us.md',
      '/compiled_docs/drawer/demo/placement.md',
      '/compiled_docs/drawer/demo/select.en-us.md',
      '/compiled_docs/drawer/demo/select.md',
    ],

    readme: [
      '/compiled_docs/drawer/index.en-us.md',
      '/compiled_docs/drawer/index.md',
    ],
  },
  'Dropdown':  {
    demos: [
      '/compiled_docs/dropdown/demo/basic.en-us.md',
      '/compiled_docs/dropdown/demo/basic.md',
      '/compiled_docs/dropdown/demo/controlled.en-us.md',
      '/compiled_docs/dropdown/demo/controlled.md',
      '/compiled_docs/dropdown/demo/trigger-type.en-us.md',
      '/compiled_docs/dropdown/demo/trigger-type.md',
    ],

    readme: [
      '/compiled_docs/dropdown/index.en-us.md',
      '/compiled_docs/dropdown/index.md',
    ],
  },
  'Field':  {
    demos: [
      '/compiled_docs/field/demo/autounmout.en-us.md',
      '/compiled_docs/field/demo/autounmout.md',
      '/compiled_docs/field/demo/basic.en-us.md',
      '/compiled_docs/field/demo/basic.md',
      '/compiled_docs/field/demo/custom.en-us.md',
      '/compiled_docs/field/demo/custom.md',
      '/compiled_docs/field/demo/dynamic.en-us.md',
      '/compiled_docs/field/demo/dynamic.md',
      '/compiled_docs/field/demo/hooks.en-us.md',
      '/compiled_docs/field/demo/hooks.md',
      '/compiled_docs/field/demo/mix.en-us.md',
      '/compiled_docs/field/demo/mix.md',
      '/compiled_docs/field/demo/normalize.en-us.md',
      '/compiled_docs/field/demo/normalize.md',
      '/compiled_docs/field/demo/onchange.en-us.md',
      '/compiled_docs/field/demo/onchange.md',
      '/compiled_docs/field/demo/redux.en-us.md',
      '/compiled_docs/field/demo/redux.md',
      '/compiled_docs/field/demo/seterror.en-us.md',
      '/compiled_docs/field/demo/seterror.md',
      '/compiled_docs/field/demo/topath.en-us.md',
      '/compiled_docs/field/demo/topath.md',
      '/compiled_docs/field/demo/validator.en-us.md',
      '/compiled_docs/field/demo/validator.md',
      '/compiled_docs/field/demo/validatorPromise.en-us.md',
      '/compiled_docs/field/demo/validatorPromise.md',
      '/compiled_docs/field/demo/valuename.en-us.md',
      '/compiled_docs/field/demo/valuename.md',
    ],

    readme: [
      '/compiled_docs/field/index.en-us.md',
      '/compiled_docs/field/index.md',
    ],
  },
  'Form':  {
    demos: [
      '/compiled_docs/form/demo/accessibility.en-us.md',
      '/compiled_docs/form/demo/accessibility.md',
      '/compiled_docs/form/demo/base.en-us.md',
      '/compiled_docs/form/demo/base.md',
      '/compiled_docs/form/demo/custom.en-us.md',
      '/compiled_docs/form/demo/custom.md',
      '/compiled_docs/form/demo/field.en-us.md',
      '/compiled_docs/form/demo/field.md',
      '/compiled_docs/form/demo/inline.en-us.md',
      '/compiled_docs/form/demo/inline.md',
      '/compiled_docs/form/demo/inset.en-us.md',
      '/compiled_docs/form/demo/inset.md',
      '/compiled_docs/form/demo/mix.en-us.md',
      '/compiled_docs/form/demo/mix.md',
      '/compiled_docs/form/demo/mobile.en-us.md',
      '/compiled_docs/form/demo/mobile.md',
      '/compiled_docs/form/demo/nest.en-us.md',
      '/compiled_docs/form/demo/nest.md',
      '/compiled_docs/form/demo/onsubmit.en-us.md',
      '/compiled_docs/form/demo/onsubmit.md',
      '/compiled_docs/form/demo/preview.en-us.md',
      '/compiled_docs/form/demo/preview.md',
      '/compiled_docs/form/demo/redux-seterror.en-us.md',
      '/compiled_docs/form/demo/redux-seterror.md',
      '/compiled_docs/form/demo/redux.en-us.md',
      '/compiled_docs/form/demo/redux.md',
      '/compiled_docs/form/demo/register.en-us.md',
      '/compiled_docs/form/demo/register.md',
      '/compiled_docs/form/demo/responsive-grid.en-us.md',
      '/compiled_docs/form/demo/responsive-grid.md',
      '/compiled_docs/form/demo/responsive.en-us.md',
      '/compiled_docs/form/demo/responsive.md',
      '/compiled_docs/form/demo/size.en-us.md',
      '/compiled_docs/form/demo/size.md',
      '/compiled_docs/form/demo/top.en-us.md',
      '/compiled_docs/form/demo/top.md',
      '/compiled_docs/form/demo/validate-basic.en-us.md',
      '/compiled_docs/form/demo/validate-basic.md',
      '/compiled_docs/form/demo/validate-custom-error.en-us.md',
      '/compiled_docs/form/demo/validate-custom-error.md',
      '/compiled_docs/form/demo/validate-label-as-name.en-us.md',
      '/compiled_docs/form/demo/validate-label-as-name.md',
      '/compiled_docs/form/demo/validate-static.en-us.md',
      '/compiled_docs/form/demo/validate-static.md',
    ],

    readme: [
      '/compiled_docs/form/index.en-us.md',
      '/compiled_docs/form/index.md',
    ],
  },
  'Grid':  {
    demos: [
      '/compiled_docs/grid/demo/align.en-us.md',
      '/compiled_docs/grid/demo/align.md',
      '/compiled_docs/grid/demo/basic.en-us.md',
      '/compiled_docs/grid/demo/basic.md',
      '/compiled_docs/grid/demo/breakpoint.en-us.md',
      '/compiled_docs/grid/demo/breakpoint.md',
      '/compiled_docs/grid/demo/custom-elem-type.en-us.md',
      '/compiled_docs/grid/demo/custom-elem-type.md',
      '/compiled_docs/grid/demo/fixed.en-us.md',
      '/compiled_docs/grid/demo/fixed.md',
      '/compiled_docs/grid/demo/gutter.en-us.md',
      '/compiled_docs/grid/demo/gutter.md',
      '/compiled_docs/grid/demo/hidden.en-us.md',
      '/compiled_docs/grid/demo/hidden.md',
      '/compiled_docs/grid/demo/justify.en-us.md',
      '/compiled_docs/grid/demo/justify.md',
      '/compiled_docs/grid/demo/nest.en-us.md',
      '/compiled_docs/grid/demo/nest.md',
      '/compiled_docs/grid/demo/offset-fixed.en-us.md',
      '/compiled_docs/grid/demo/offset-fixed.md',
      '/compiled_docs/grid/demo/offset.en-us.md',
      '/compiled_docs/grid/demo/offset.md',
      '/compiled_docs/grid/demo/type.en-us.md',
      '/compiled_docs/grid/demo/type.md',
      '/compiled_docs/grid/demo/wrap.en-us.md',
      '/compiled_docs/grid/demo/wrap.md',
    ],

    readme: [
      '/compiled_docs/grid/index.en-us.md',
      '/compiled_docs/grid/index.md',
    ],
  },
  'Icon':  {
    demos: [
      '/compiled_docs/icon/demo/accessibility.en-us.md',
      '/compiled_docs/icon/demo/accessibility.md',
      '/compiled_docs/icon/demo/basic.en-us.md',
      '/compiled_docs/icon/demo/basic.md',
      '/compiled_docs/icon/demo/iconfont.en-us.md',
      '/compiled_docs/icon/demo/iconfont.md',
      '/compiled_docs/icon/demo/size.en-us.md',
      '/compiled_docs/icon/demo/size.md',
      '/compiled_docs/icon/demo/style.en-us.md',
      '/compiled_docs/icon/demo/style.md',
      '/compiled_docs/icon/demo/type.en-us.md',
      '/compiled_docs/icon/demo/type.md',
    ],

    readme: [
      '/compiled_docs/icon/index.en-us.md',
      '/compiled_docs/icon/index.md',
    ],
  },
  'Input':  {
    demos: [
      '/compiled_docs/input/demo/accessibility.en-us.md',
      '/compiled_docs/input/demo/accessibility.md',
      '/compiled_docs/input/demo/addon.en-us.md',
      '/compiled_docs/input/demo/addon.md',
      '/compiled_docs/input/demo/autoheight.en-us.md',
      '/compiled_docs/input/demo/autoheight.md',
      '/compiled_docs/input/demo/basic.en-us.md',
      '/compiled_docs/input/demo/basic.md',
      '/compiled_docs/input/demo/clear.en-us.md',
      '/compiled_docs/input/demo/clear.md',
      '/compiled_docs/input/demo/disabled.en-us.md',
      '/compiled_docs/input/demo/disabled.md',
      '/compiled_docs/input/demo/group.en-us.md',
      '/compiled_docs/input/demo/group.md',
      '/compiled_docs/input/demo/inner.en-us.md',
      '/compiled_docs/input/demo/inner.md',
      '/compiled_docs/input/demo/maxlen.en-us.md',
      '/compiled_docs/input/demo/maxlen.md',
      '/compiled_docs/input/demo/passwd.en-us.md',
      '/compiled_docs/input/demo/passwd.md',
      '/compiled_docs/input/demo/state.en-us.md',
      '/compiled_docs/input/demo/state.md',
      '/compiled_docs/input/demo/style.en-us.md',
      '/compiled_docs/input/demo/style.md',
      '/compiled_docs/input/demo/trim.en-us.md',
      '/compiled_docs/input/demo/trim.md',
    ],

    readme: [
      '/compiled_docs/input/index.en-us.md',
      '/compiled_docs/input/index.md',
    ],
  },
  'List':  {
    demos: [
      '/compiled_docs/list/demo/basic.en-us.md',
      '/compiled_docs/list/demo/basic.md',
      '/compiled_docs/list/demo/complex.en-us.md',
      '/compiled_docs/list/demo/complex.md',
    ],

    readme: [
      '/compiled_docs/list/index.en-us.md',
      '/compiled_docs/list/index.md',
    ],
  },
  'Loading':  {
    demos: [
      '/compiled_docs/loading/demo/basic.en-us.md',
      '/compiled_docs/loading/demo/basic.md',
      '/compiled_docs/loading/demo/fullscreen.en-us.md',
      '/compiled_docs/loading/demo/fullscreen.md',
      '/compiled_docs/loading/demo/indicator.en-us.md',
      '/compiled_docs/loading/demo/indicator.md',
      '/compiled_docs/loading/demo/size.en-us.md',
      '/compiled_docs/loading/demo/size.md',
      '/compiled_docs/loading/demo/state.en-us.md',
      '/compiled_docs/loading/demo/state.md',
      '/compiled_docs/loading/demo/tipAlign.en-us.md',
      '/compiled_docs/loading/demo/tipAlign.md',
    ],

    readme: [
      '/compiled_docs/loading/index.en-us.md',
      '/compiled_docs/loading/index.md',
    ],
  },
  'Menu':  {
    demos: [
      '/compiled_docs/menu/demo/accordian.en-us.md',
      '/compiled_docs/menu/demo/accordian.md',
      '/compiled_docs/menu/demo/basic.en-us.md',
      '/compiled_docs/menu/demo/basic.md',
      '/compiled_docs/menu/demo/context.en-us.md',
      '/compiled_docs/menu/demo/context.md',
      '/compiled_docs/menu/demo/csutom-select.en-us.md',
      '/compiled_docs/menu/demo/csutom-select.md',
      '/compiled_docs/menu/demo/custom-popup.en-us.md',
      '/compiled_docs/menu/demo/custom-popup.md',
      '/compiled_docs/menu/demo/hover.en-us.md',
      '/compiled_docs/menu/demo/hover.md',
      '/compiled_docs/menu/demo/hoz.en-us.md',
      '/compiled_docs/menu/demo/hoz.md',
      '/compiled_docs/menu/demo/popup-align.en-us.md',
      '/compiled_docs/menu/demo/popup-align.md',
      '/compiled_docs/menu/demo/popup.en-us.md',
      '/compiled_docs/menu/demo/popup.md',
      '/compiled_docs/menu/demo/render-more.en-us.md',
      '/compiled_docs/menu/demo/render-more.md',
      '/compiled_docs/menu/demo/select.en-us.md',
      '/compiled_docs/menu/demo/select.md',
    ],

    readme: [
      '/compiled_docs/menu/index.en-us.md',
      '/compiled_docs/menu/index.md',
    ],
  },
  'MenuButton':  {
    demos: [
      '/compiled_docs/menu-button/demo/basic.en-us.md',
      '/compiled_docs/menu-button/demo/basic.md',
      '/compiled_docs/menu-button/demo/menu.en-us.md',
      '/compiled_docs/menu-button/demo/menu.md',
      '/compiled_docs/menu-button/demo/select.en-us.md',
      '/compiled_docs/menu-button/demo/select.md',
      '/compiled_docs/menu-button/demo/size.en-us.md',
      '/compiled_docs/menu-button/demo/size.md',
    ],

    readme: [
      '/compiled_docs/menu-button/index.en-us.md',
      '/compiled_docs/menu-button/index.md',
    ],
  },
  'Message':  {
    demos: [
      '/compiled_docs/message/demo/accessibility.en-us.md',
      '/compiled_docs/message/demo/accessibility.md',
      '/compiled_docs/message/demo/control.en-us.md',
      '/compiled_docs/message/demo/control.md',
      '/compiled_docs/message/demo/inline-close.en-us.md',
      '/compiled_docs/message/demo/inline-close.md',
      '/compiled_docs/message/demo/shape.en-us.md',
      '/compiled_docs/message/demo/shape.md',
      '/compiled_docs/message/demo/size.en-us.md',
      '/compiled_docs/message/demo/size.md',
      '/compiled_docs/message/demo/toast-quick.en-us.md',
      '/compiled_docs/message/demo/toast-quick.md',
      '/compiled_docs/message/demo/toast.en-us.md',
      '/compiled_docs/message/demo/toast.md',
      '/compiled_docs/message/demo/type.en-us.md',
      '/compiled_docs/message/demo/type.md',
    ],

    readme: [
      '/compiled_docs/message/index.en-us.md',
      '/compiled_docs/message/index.md',
    ],
  },
  'Nav':  {
    demos: [
      '/compiled_docs/nav/demo/basic.en-us.md',
      '/compiled_docs/nav/demo/basic.md',
      '/compiled_docs/nav/demo/custom.en-us.md',
      '/compiled_docs/nav/demo/custom.md',
      '/compiled_docs/nav/demo/fixed.en-us.md',
      '/compiled_docs/nav/demo/fixed.md',
      '/compiled_docs/nav/demo/group.en-us.md',
      '/compiled_docs/nav/demo/group.md',
      '/compiled_docs/nav/demo/icon-only.en-us.md',
      '/compiled_docs/nav/demo/icon-only.md',
      '/compiled_docs/nav/demo/open-mode.en-us.md',
      '/compiled_docs/nav/demo/open-mode.md',
      '/compiled_docs/nav/demo/popup-align.en-us.md',
      '/compiled_docs/nav/demo/popup-align.md',
    ],

    readme: [
      '/compiled_docs/nav/index.en-us.md',
      '/compiled_docs/nav/index.md',
    ],
  },
  'Notification':  {
    demos: [
      '/compiled_docs/notification/demo/basic.en-us.md',
      '/compiled_docs/notification/demo/basic.md',
      '/compiled_docs/notification/demo/duration.en-us.md',
      '/compiled_docs/notification/demo/duration.md',
      '/compiled_docs/notification/demo/icon.en-us.md',
      '/compiled_docs/notification/demo/icon.md',
      '/compiled_docs/notification/demo/level.en-us.md',
      '/compiled_docs/notification/demo/level.md',
      '/compiled_docs/notification/demo/position.en-us.md',
      '/compiled_docs/notification/demo/position.md',
      '/compiled_docs/notification/demo/style.en-us.md',
      '/compiled_docs/notification/demo/style.md',
      '/compiled_docs/notification/demo/update.en-us.md',
      '/compiled_docs/notification/demo/update.md',
    ],

    readme: [
      '/compiled_docs/notification/index.en-us.md',
      '/compiled_docs/notification/index.md',
    ],
  },
  'NumberPicker':  {
    demos: [
      '/compiled_docs/number-picker/demo/accessibility.en-us.md',
      '/compiled_docs/number-picker/demo/accessibility.md',
      '/compiled_docs/number-picker/demo/basic.en-us.md',
      '/compiled_docs/number-picker/demo/basic.md',
      '/compiled_docs/number-picker/demo/disabled.en-us.md',
      '/compiled_docs/number-picker/demo/disabled.md',
      '/compiled_docs/number-picker/demo/editable.en-us.md',
      '/compiled_docs/number-picker/demo/editable.md',
      '/compiled_docs/number-picker/demo/format.en-us.md',
      '/compiled_docs/number-picker/demo/format.md',
      '/compiled_docs/number-picker/demo/limit.en-us.md',
      '/compiled_docs/number-picker/demo/limit.md',
      '/compiled_docs/number-picker/demo/mobile.en-us.md',
      '/compiled_docs/number-picker/demo/mobile.md',
      '/compiled_docs/number-picker/demo/precision.en-us.md',
      '/compiled_docs/number-picker/demo/precision.md',
      '/compiled_docs/number-picker/demo/size.en-us.md',
      '/compiled_docs/number-picker/demo/size.md',
      '/compiled_docs/number-picker/demo/step.en-us.md',
      '/compiled_docs/number-picker/demo/step.md',
      '/compiled_docs/number-picker/demo/trigger.en-us.md',
      '/compiled_docs/number-picker/demo/trigger.md',
    ],

    readme: [
      '/compiled_docs/number-picker/index.en-us.md',
      '/compiled_docs/number-picker/index.md',
    ],
  },
  'Overlay':  {
    demos: [
      '/compiled_docs/overlay/demo/align.en-us.md',
      '/compiled_docs/overlay/demo/align.md',
      '/compiled_docs/overlay/demo/backdrop.en-us.md',
      '/compiled_docs/overlay/demo/backdrop.md',
      '/compiled_docs/overlay/demo/controlled.en-us.md',
      '/compiled_docs/overlay/demo/controlled.md',
      '/compiled_docs/overlay/demo/nested.en-us.md',
      '/compiled_docs/overlay/demo/nested.md',
      '/compiled_docs/overlay/demo/overlay.en-us.md',
      '/compiled_docs/overlay/demo/overlay.md',
      '/compiled_docs/overlay/demo/popup.en-us.md',
      '/compiled_docs/overlay/demo/popup.md',
      '/compiled_docs/overlay/demo/scroll.en-us.md',
      '/compiled_docs/overlay/demo/scroll.md',
    ],

    readme: [
      '/compiled_docs/overlay/index.en-us.md',
      '/compiled_docs/overlay/index.md',
    ],
  },
  'Pagination':  {
    demos: [
      '/compiled_docs/pagination/demo/control.en-us.md',
      '/compiled_docs/pagination/demo/control.md',
      '/compiled_docs/pagination/demo/dropdown-direction.en-us.md',
      '/compiled_docs/pagination/demo/dropdown-direction.md',
      '/compiled_docs/pagination/demo/link.en-us.md',
      '/compiled_docs/pagination/demo/link.md',
      '/compiled_docs/pagination/demo/page-size.en-us.md',
      '/compiled_docs/pagination/demo/page-size.md',
      '/compiled_docs/pagination/demo/react-router.en-us.md',
      '/compiled_docs/pagination/demo/react-router.md',
      '/compiled_docs/pagination/demo/shape.en-us.md',
      '/compiled_docs/pagination/demo/shape.md',
      '/compiled_docs/pagination/demo/show-total.en-us.md',
      '/compiled_docs/pagination/demo/show-total.md',
      '/compiled_docs/pagination/demo/size.en-us.md',
      '/compiled_docs/pagination/demo/size.md',
      '/compiled_docs/pagination/demo/type.en-us.md',
      '/compiled_docs/pagination/demo/type.md',
      '/compiled_docs/pagination/demo/uncontrol.en-us.md',
      '/compiled_docs/pagination/demo/uncontrol.md',
    ],

    readme: [
      '/compiled_docs/pagination/index.en-us.md',
      '/compiled_docs/pagination/index.md',
    ],
  },
  'Paragraph':  {
    demos: [
      '/compiled_docs/paragraph/demo/basic.en-us.md',
      '/compiled_docs/paragraph/demo/basic.md',
      '/compiled_docs/paragraph/demo/type.en-us.md',
      '/compiled_docs/paragraph/demo/type.md',
    ],

    readme: [
      '/compiled_docs/paragraph/index.en-us.md',
      '/compiled_docs/paragraph/index.md',
    ],
  },
  'Progress':  {
    demos: [
      '/compiled_docs/progress/demo/basic.en-us.md',
      '/compiled_docs/progress/demo/basic.md',
      '/compiled_docs/progress/demo/circle.en-us.md',
      '/compiled_docs/progress/demo/circle.md',
      '/compiled_docs/progress/demo/color.en-us.md',
      '/compiled_docs/progress/demo/color.md',
      '/compiled_docs/progress/demo/controlled.en-us.md',
      '/compiled_docs/progress/demo/controlled.md',
      '/compiled_docs/progress/demo/percentrender.en-us.md',
      '/compiled_docs/progress/demo/percentrender.md',
      '/compiled_docs/progress/demo/progressive.en-us.md',
      '/compiled_docs/progress/demo/progressive.md',
      '/compiled_docs/progress/demo/size.en-us.md',
      '/compiled_docs/progress/demo/size.md',
      '/compiled_docs/progress/demo/state.en-us.md',
      '/compiled_docs/progress/demo/state.md',
    ],

    readme: [
      '/compiled_docs/progress/index.en-us.md',
      '/compiled_docs/progress/index.md',
    ],
  },
  'Radio':  {
    demos: [
      '/compiled_docs/radio/demo/accessibility.en-us.md',
      '/compiled_docs/radio/demo/accessibility.md',
      '/compiled_docs/radio/demo/basic.en-us.md',
      '/compiled_docs/radio/demo/basic.md',
      '/compiled_docs/radio/demo/button.en-us.md',
      '/compiled_docs/radio/demo/button.md',
      '/compiled_docs/radio/demo/control.en-us.md',
      '/compiled_docs/radio/demo/control.md',
      '/compiled_docs/radio/demo/group.en-us.md',
      '/compiled_docs/radio/demo/group.md',
      '/compiled_docs/radio/demo/nest.en-us.md',
      '/compiled_docs/radio/demo/nest.md',
      '/compiled_docs/radio/demo/uncontrol.en-us.md',
      '/compiled_docs/radio/demo/uncontrol.md',
      '/compiled_docs/radio/demo/useWithGrid.en-us.md',
      '/compiled_docs/radio/demo/useWithGrid.md',
    ],

    readme: [
      '/compiled_docs/radio/index.en-us.md',
      '/compiled_docs/radio/index.md',
    ],
  },
  'Range':  {
    demos: [
      '/compiled_docs/range/demo/accessibility.en-us.md',
      '/compiled_docs/range/demo/accessibility.md',
      '/compiled_docs/range/demo/basic.en-us.md',
      '/compiled_docs/range/demo/basic.md',
      '/compiled_docs/range/demo/change.en-us.md',
      '/compiled_docs/range/demo/change.md',
      '/compiled_docs/range/demo/control.en-us.md',
      '/compiled_docs/range/demo/control.md',
      '/compiled_docs/range/demo/fixedWidth.en-us.md',
      '/compiled_docs/range/demo/fixedWidth.md',
      '/compiled_docs/range/demo/marks.en-us.md',
      '/compiled_docs/range/demo/marks.md',
      '/compiled_docs/range/demo/range.en-us.md',
      '/compiled_docs/range/demo/range.md',
      '/compiled_docs/range/demo/reverse.en-us.md',
      '/compiled_docs/range/demo/reverse.md',
      '/compiled_docs/range/demo/tipRender.en-us.md',
      '/compiled_docs/range/demo/tipRender.md',
    ],

    readme: [
      '/compiled_docs/range/index.en-us.md',
      '/compiled_docs/range/index.md',
    ],
  },
  'Rating':  {
    demos: [
      '/compiled_docs/rating/demo/accessibility.en-us.md',
      '/compiled_docs/rating/demo/accessibility.md',
      '/compiled_docs/rating/demo/basic.en-us.md',
      '/compiled_docs/rating/demo/basic.md',
      '/compiled_docs/rating/demo/disabled.en-us.md',
      '/compiled_docs/rating/demo/disabled.md',
      '/compiled_docs/rating/demo/grade.en-us.md',
      '/compiled_docs/rating/demo/grade.md',
      '/compiled_docs/rating/demo/half.en-us.md',
      '/compiled_docs/rating/demo/half.md',
      '/compiled_docs/rating/demo/size.en-us.md',
      '/compiled_docs/rating/demo/size.md',
    ],

    readme: [
      '/compiled_docs/rating/index.en-us.md',
      '/compiled_docs/rating/index.md',
    ],
  },
  'ResponsiveGrid':  {
    demos: [
      '/compiled_docs/responsive-grid/demo/basic.en-us.md',
      '/compiled_docs/responsive-grid/demo/basic.md',
    ],

    readme: [
      '/compiled_docs/responsive-grid/index.en-us.md',
      '/compiled_docs/responsive-grid/index.md',
    ],
  },
  'Search':  {
    demos: [
      '/compiled_docs/search/demo/accessibility.en-us.md',
      '/compiled_docs/search/demo/accessibility.md',
      '/compiled_docs/search/demo/base.en-us.md',
      '/compiled_docs/search/demo/base.md',
      '/compiled_docs/search/demo/combobox.en-us.md',
      '/compiled_docs/search/demo/combobox.md',
      '/compiled_docs/search/demo/custom.en-us.md',
      '/compiled_docs/search/demo/custom.md',
      '/compiled_docs/search/demo/filter.en-us.md',
      '/compiled_docs/search/demo/filter.md',
      '/compiled_docs/search/demo/size.en-us.md',
      '/compiled_docs/search/demo/size.md',
      '/compiled_docs/search/demo/type.en-us.md',
      '/compiled_docs/search/demo/type.md',
    ],

    readme: [
      '/compiled_docs/search/index.en-us.md',
      '/compiled_docs/search/index.md',
    ],
  },
  'Select':  {
    demos: [
      '/compiled_docs/select/demo/accessibility.en-us.md',
      '/compiled_docs/select/demo/accessibility.md',
      '/compiled_docs/select/demo/basic.en-us.md',
      '/compiled_docs/select/demo/basic.md',
      '/compiled_docs/select/demo/combobox-basic.en-us.md',
      '/compiled_docs/select/demo/combobox-basic.md',
      '/compiled_docs/select/demo/combobox-fillprops.en-us.md',
      '/compiled_docs/select/demo/combobox-fillprops.md',
      '/compiled_docs/select/demo/combobox-remote.en-us.md',
      '/compiled_docs/select/demo/combobox-remote.md',
      '/compiled_docs/select/demo/combobox-rich-text.en-us.md',
      '/compiled_docs/select/demo/combobox-rich-text.md',
      '/compiled_docs/select/demo/combobox.en-us.md',
      '/compiled_docs/select/demo/combobox.md',
      '/compiled_docs/select/demo/customize-menu.en-us.md',
      '/compiled_docs/select/demo/customize-menu.md',
      '/compiled_docs/select/demo/customize-overlay.en-us.md',
      '/compiled_docs/select/demo/customize-overlay.md',
      '/compiled_docs/select/demo/max-count.en-us.md',
      '/compiled_docs/select/demo/max-count.md',
      '/compiled_docs/select/demo/multiple.en-us.md',
      '/compiled_docs/select/demo/multiple.md',
      '/compiled_docs/select/demo/select-basic.en-us.md',
      '/compiled_docs/select/demo/select-basic.md',
      '/compiled_docs/select/demo/select-cascader.en-us.md',
      '/compiled_docs/select/demo/select-cascader.md',
      '/compiled_docs/select/demo/select-custom-menu.en-us.md',
      '/compiled_docs/select/demo/select-custom-menu.md',
      '/compiled_docs/select/demo/select-custom-value.en-us.md',
      '/compiled_docs/select/demo/select-custom-value.md',
      '/compiled_docs/select/demo/select-label.en-us.md',
      '/compiled_docs/select/demo/select-label.md',
      '/compiled_docs/select/demo/select-options-group.en-us.md',
      '/compiled_docs/select/demo/select-options-group.md',
      '/compiled_docs/select/demo/select-search.en-us.md',
      '/compiled_docs/select/demo/select-search.md',
      '/compiled_docs/select/demo/tag.en-us.md',
      '/compiled_docs/select/demo/tag.md',
      '/compiled_docs/select/demo/use-detail-value.en-us.md',
      '/compiled_docs/select/demo/use-detail-value.md',
      '/compiled_docs/select/demo/virtual-select.en-us.md',
      '/compiled_docs/select/demo/virtual-select.md',
    ],

    readme: [
      '/compiled_docs/select/index.en-us.md',
      '/compiled_docs/select/index.md',
    ],
  },
  'Shell':  {
    demos: [
      '/compiled_docs/shell/demo/basic.en-us.md',
      '/compiled_docs/shell/demo/basic.md',
      '/compiled_docs/shell/demo/complicated.en-us.md',
      '/compiled_docs/shell/demo/complicated.md',
      '/compiled_docs/shell/demo/header-global-local.en-us.md',
      '/compiled_docs/shell/demo/header-global-local.md',
      '/compiled_docs/shell/demo/header-global.en-us.md',
      '/compiled_docs/shell/demo/header-global.md',
    ],

    readme: [
      '/compiled_docs/shell/index.en-us.md',
      '/compiled_docs/shell/index.md',
    ],
  },
  'Slider':  {
    demos: [
      '/compiled_docs/slider/demo/arrow-position.en-us.md',
      '/compiled_docs/slider/demo/arrow-position.md',
      '/compiled_docs/slider/demo/autoplay.en-us.md',
      '/compiled_docs/slider/demo/autoplay.md',
      '/compiled_docs/slider/demo/basic.en-us.md',
      '/compiled_docs/slider/demo/basic.md',
      '/compiled_docs/slider/demo/button-size.en-us.md',
      '/compiled_docs/slider/demo/button-size.md',
      '/compiled_docs/slider/demo/center-mode.en-us.md',
      '/compiled_docs/slider/demo/center-mode.md',
      '/compiled_docs/slider/demo/custom-arrow.en-us.md',
      '/compiled_docs/slider/demo/custom-arrow.md',
      '/compiled_docs/slider/demo/custom-slide.en-us.md',
      '/compiled_docs/slider/demo/custom-slide.md',
      '/compiled_docs/slider/demo/dots-direction.en-us.md',
      '/compiled_docs/slider/demo/dots-direction.md',
      '/compiled_docs/slider/demo/dots-render.en-us.md',
      '/compiled_docs/slider/demo/dots-render.md',
      '/compiled_docs/slider/demo/dots-triggerType.en-us.md',
      '/compiled_docs/slider/demo/dots-triggerType.md',
      '/compiled_docs/slider/demo/fade.en-us.md',
      '/compiled_docs/slider/demo/fade.md',
      '/compiled_docs/slider/demo/infinite.en-us.md',
      '/compiled_docs/slider/demo/infinite.md',
      '/compiled_docs/slider/demo/multiple.en-us.md',
      '/compiled_docs/slider/demo/multiple.md',
      '/compiled_docs/slider/demo/pause-on-hover.en-us.md',
      '/compiled_docs/slider/demo/pause-on-hover.md',
      '/compiled_docs/slider/demo/slick-goto.en-us.md',
      '/compiled_docs/slider/demo/slick-goto.md',
      '/compiled_docs/slider/demo/slide-change-hook.en-us.md',
      '/compiled_docs/slider/demo/slide-change-hook.md',
      '/compiled_docs/slider/demo/slide-direction.en-us.md',
      '/compiled_docs/slider/demo/slide-direction.md',
      '/compiled_docs/slider/demo/slider-with-dialog.en-us.md',
      '/compiled_docs/slider/demo/slider-with-dialog.md',
      '/compiled_docs/slider/demo/slider-wrapper.en-us.md',
      '/compiled_docs/slider/demo/slider-wrapper.md',
      '/compiled_docs/slider/demo/variable-width.en-us.md',
      '/compiled_docs/slider/demo/variable-width.md',
    ],

    readme: [
      '/compiled_docs/slider/index.en-us.md',
      '/compiled_docs/slider/index.md',
    ],
  },
  'SplitButton':  {
    demos: [
      '/compiled_docs/split-button/demo/accessibility.en-us.md',
      '/compiled_docs/split-button/demo/accessibility.md',
      '/compiled_docs/split-button/demo/basic.en-us.md',
      '/compiled_docs/split-button/demo/basic.md',
      '/compiled_docs/split-button/demo/composite.en-us.md',
      '/compiled_docs/split-button/demo/composite.md',
      '/compiled_docs/split-button/demo/menu.en-us.md',
      '/compiled_docs/split-button/demo/menu.md',
      '/compiled_docs/split-button/demo/size.en-us.md',
      '/compiled_docs/split-button/demo/size.md',
    ],

    readme: [
      '/compiled_docs/split-button/index.en-us.md',
      '/compiled_docs/split-button/index.md',
    ],
  },
  'Step':  {
    demos: [
      '/compiled_docs/step/demo/basic.en-us.md',
      '/compiled_docs/step/demo/basic.md',
      '/compiled_docs/step/demo/controlled.en-us.md',
      '/compiled_docs/step/demo/controlled.md',
      '/compiled_docs/step/demo/custom-step-item.en-us.md',
      '/compiled_docs/step/demo/custom-step-item.md',
      '/compiled_docs/step/demo/direction.en-us.md',
      '/compiled_docs/step/demo/direction.md',
      '/compiled_docs/step/demo/disable.en-us.md',
      '/compiled_docs/step/demo/disable.md',
      '/compiled_docs/step/demo/percent.en-us.md',
      '/compiled_docs/step/demo/percent.md',
      '/compiled_docs/step/demo/read-only.en-us.md',
      '/compiled_docs/step/demo/read-only.md',
    ],

    readme: [
      '/compiled_docs/step/index.en-us.md',
      '/compiled_docs/step/index.md',
    ],
  },
  'Switch':  {
    demos: [
      '/compiled_docs/switch/demo/accessibility.en-us.md',
      '/compiled_docs/switch/demo/accessibility.md',
      '/compiled_docs/switch/demo/basic.en-us.md',
      '/compiled_docs/switch/demo/basic.md',
      '/compiled_docs/switch/demo/control.en-us.md',
      '/compiled_docs/switch/demo/control.md',
      '/compiled_docs/switch/demo/disabled.en-us.md',
      '/compiled_docs/switch/demo/disabled.md',
    ],

    readme: [
      '/compiled_docs/switch/index.en-us.md',
      '/compiled_docs/switch/index.md',
    ],
  },
  'Tab':  {
    demos: [
      '/compiled_docs/tab/demo/basic.en-us.md',
      '/compiled_docs/tab/demo/basic.md',
      '/compiled_docs/tab/demo/closable.en-us.md',
      '/compiled_docs/tab/demo/closable.md',
      '/compiled_docs/tab/demo/custom-style.en-us.md',
      '/compiled_docs/tab/demo/custom-style.md',
      '/compiled_docs/tab/demo/custom-tab.en-us.md',
      '/compiled_docs/tab/demo/custom-tab.md',
      '/compiled_docs/tab/demo/disabled.en-us.md',
      '/compiled_docs/tab/demo/disabled.md',
      '/compiled_docs/tab/demo/editable-tab.en-us.md',
      '/compiled_docs/tab/demo/editable-tab.md',
      '/compiled_docs/tab/demo/excess-mode.en-us.md',
      '/compiled_docs/tab/demo/excess-mode.md',
      '/compiled_docs/tab/demo/extra.en-us.md',
      '/compiled_docs/tab/demo/extra.md',
      '/compiled_docs/tab/demo/lazy-load.en-us.md',
      '/compiled_docs/tab/demo/lazy-load.md',
      '/compiled_docs/tab/demo/nested.en-us.md',
      '/compiled_docs/tab/demo/nested.md',
      '/compiled_docs/tab/demo/position.en-us.md',
      '/compiled_docs/tab/demo/position.md',
      '/compiled_docs/tab/demo/shape.en-us.md',
      '/compiled_docs/tab/demo/shape.md',
      '/compiled_docs/tab/demo/size.en-us.md',
      '/compiled_docs/tab/demo/size.md',
      '/compiled_docs/tab/demo/tab-in-grid.en-us.md',
      '/compiled_docs/tab/demo/tab-in-grid.md',
      '/compiled_docs/tab/demo/trigger-type.en-us.md',
      '/compiled_docs/tab/demo/trigger-type.md',
    ],

    readme: [
      '/compiled_docs/tab/index.en-us.md',
      '/compiled_docs/tab/index.md',
    ],
  },
  'Table':  {
    demos: [
      '/compiled_docs/table/demo/accessibility.en-us.md',
      '/compiled_docs/table/demo/accessibility.md',
      '/compiled_docs/table/demo/advanced.en-us.md',
      '/compiled_docs/table/demo/advanced.md',
      '/compiled_docs/table/demo/basic.en-us.md',
      '/compiled_docs/table/demo/basic.md',
      '/compiled_docs/table/demo/clear-selection.en-us.md',
      '/compiled_docs/table/demo/clear-selection.md',
      '/compiled_docs/table/demo/colspan-lock-columns.en-us.md',
      '/compiled_docs/table/demo/colspan-lock-columns.md',
      '/compiled_docs/table/demo/colspan.en-us.md',
      '/compiled_docs/table/demo/colspan.md',
      '/compiled_docs/table/demo/column.en-us.md',
      '/compiled_docs/table/demo/column.md',
      '/compiled_docs/table/demo/crossline.en-us.md',
      '/compiled_docs/table/demo/crossline.md',
      '/compiled_docs/table/demo/crud.en-us.md',
      '/compiled_docs/table/demo/crud.md',
      '/compiled_docs/table/demo/custom-loading.en-us.md',
      '/compiled_docs/table/demo/custom-loading.md',
      '/compiled_docs/table/demo/dragable.en-us.md',
      '/compiled_docs/table/demo/dragable.md',
      '/compiled_docs/table/demo/editable.en-us.md',
      '/compiled_docs/table/demo/editable.md',
      '/compiled_docs/table/demo/expanded-complex.en-us.md',
      '/compiled_docs/table/demo/expanded-complex.md',
      '/compiled_docs/table/demo/expanded.en-us.md',
      '/compiled_docs/table/demo/expanded.md',
      '/compiled_docs/table/demo/filter&sort.en-us.md',
      '/compiled_docs/table/demo/filter&sort.md',
      '/compiled_docs/table/demo/fixed-header.en-us.md',
      '/compiled_docs/table/demo/fixed-header.md',
      '/compiled_docs/table/demo/get-row-props.en-us.md',
      '/compiled_docs/table/demo/get-row-props.md',
      '/compiled_docs/table/demo/list.en-us.md',
      '/compiled_docs/table/demo/list.md',
      '/compiled_docs/table/demo/lock-column.en-us.md',
      '/compiled_docs/table/demo/lock-column.md',
      '/compiled_docs/table/demo/mix.en-us.md',
      '/compiled_docs/table/demo/mix.md',
      '/compiled_docs/table/demo/multiple-header.en-us.md',
      '/compiled_docs/table/demo/multiple-header.md',
      '/compiled_docs/table/demo/pagination.en-us.md',
      '/compiled_docs/table/demo/pagination.md',
      '/compiled_docs/table/demo/resize.en-us.md',
      '/compiled_docs/table/demo/resize.md',
      '/compiled_docs/table/demo/row-selection-config.en-us.md',
      '/compiled_docs/table/demo/row-selection-config.md',
      '/compiled_docs/table/demo/selection.en-us.md',
      '/compiled_docs/table/demo/selection.md',
      '/compiled_docs/table/demo/style.en-us.md',
      '/compiled_docs/table/demo/style.md',
      '/compiled_docs/table/demo/virtual.en-us.md',
      '/compiled_docs/table/demo/virtual.md',
    ],

    readme: [
      '/compiled_docs/table/index.en-us.md',
      '/compiled_docs/table/index.md',
    ],
  },
  'Tag':  {
    demos: [
      '/compiled_docs/tag/demo/accessibility.en-us.md',
      '/compiled_docs/tag/demo/accessibility.md',
      '/compiled_docs/tag/demo/basic.en-us.md',
      '/compiled_docs/tag/demo/basic.md',
      '/compiled_docs/tag/demo/closable.en-us.md',
      '/compiled_docs/tag/demo/closable.md',
      '/compiled_docs/tag/demo/colorful-tag.en-us.md',
      '/compiled_docs/tag/demo/colorful-tag.md',
      '/compiled_docs/tag/demo/selectable.en-us.md',
      '/compiled_docs/tag/demo/selectable.md',
    ],

    readme: [
      '/compiled_docs/tag/index.en-us.md',
      '/compiled_docs/tag/index.md',
    ],
  },
  'TimePicker':  {
    demos: [
      '/compiled_docs/time-picker/demo/basic.en-us.md',
      '/compiled_docs/time-picker/demo/basic.md',
      '/compiled_docs/time-picker/demo/default-value.en-us.md',
      '/compiled_docs/time-picker/demo/default-value.md',
      '/compiled_docs/time-picker/demo/disabled.en-us.md',
      '/compiled_docs/time-picker/demo/disabled.md',
      '/compiled_docs/time-picker/demo/field.en-us.md',
      '/compiled_docs/time-picker/demo/field.md',
      '/compiled_docs/time-picker/demo/format.en-us.md',
      '/compiled_docs/time-picker/demo/format.md',
      '/compiled_docs/time-picker/demo/render-menu.en-us.md',
      '/compiled_docs/time-picker/demo/render-menu.md',
      '/compiled_docs/time-picker/demo/size.en-us.md',
      '/compiled_docs/time-picker/demo/size.md',
      '/compiled_docs/time-picker/demo/step.en-us.md',
      '/compiled_docs/time-picker/demo/step.md',
      '/compiled_docs/time-picker/demo/value.en-us.md',
      '/compiled_docs/time-picker/demo/value.md',
    ],

    readme: [
      '/compiled_docs/time-picker/index.en-us.md',
      '/compiled_docs/time-picker/index.md',
    ],
  },
  'Timeline':  {
    demos: [
      '/compiled_docs/timeline/demo/basic.en-us.md',
      '/compiled_docs/timeline/demo/basic.md',
      '/compiled_docs/timeline/demo/content.en-us.md',
      '/compiled_docs/timeline/demo/content.md',
      '/compiled_docs/timeline/demo/custom.en-us.md',
      '/compiled_docs/timeline/demo/custom.md',
      '/compiled_docs/timeline/demo/fold.en-us.md',
      '/compiled_docs/timeline/demo/fold.md',
      '/compiled_docs/timeline/demo/state.en-us.md',
      '/compiled_docs/timeline/demo/state.md',
      '/compiled_docs/timeline/demo/timeLeft.en-us.md',
      '/compiled_docs/timeline/demo/timeLeft.md',
    ],

    readme: [
      '/compiled_docs/timeline/index.en-us.md',
      '/compiled_docs/timeline/index.md',
    ],
  },
  'Transfer':  {
    demos: [
      '/compiled_docs/transfer/demo/accessibility.en-us.md',
      '/compiled_docs/transfer/demo/accessibility.md',
      '/compiled_docs/transfer/demo/basic.en-us.md',
      '/compiled_docs/transfer/demo/basic.md',
      '/compiled_docs/transfer/demo/control.en-us.md',
      '/compiled_docs/transfer/demo/control.md',
      '/compiled_docs/transfer/demo/custom-panel.en-us.md',
      '/compiled_docs/transfer/demo/custom-panel.md',
      '/compiled_docs/transfer/demo/custom.en-us.md',
      '/compiled_docs/transfer/demo/custom.md',
      '/compiled_docs/transfer/demo/search.en-us.md',
      '/compiled_docs/transfer/demo/search.md',
      '/compiled_docs/transfer/demo/simple.en-us.md',
      '/compiled_docs/transfer/demo/simple.md',
      '/compiled_docs/transfer/demo/sortable.en-us.md',
      '/compiled_docs/transfer/demo/sortable.md',
    ],

    readme: [
      '/compiled_docs/transfer/index.en-us.md',
      '/compiled_docs/transfer/index.md',
    ],
  },
  'Tree':  {
    demos: [
      '/compiled_docs/tree/demo/basic.en-us.md',
      '/compiled_docs/tree/demo/basic.md',
      '/compiled_docs/tree/demo/control-check.en-us.md',
      '/compiled_docs/tree/demo/control-check.md',
      '/compiled_docs/tree/demo/control-select.en-us.md',
      '/compiled_docs/tree/demo/control-select.md',
      '/compiled_docs/tree/demo/data.en-us.md',
      '/compiled_docs/tree/demo/data.md',
      '/compiled_docs/tree/demo/draggable.en-us.md',
      '/compiled_docs/tree/demo/draggable.md',
      '/compiled_docs/tree/demo/dynamic.en-us.md',
      '/compiled_docs/tree/demo/dynamic.md',
      '/compiled_docs/tree/demo/line.en-us.md',
      '/compiled_docs/tree/demo/line.md',
      '/compiled_docs/tree/demo/node-block.en-us.md',
      '/compiled_docs/tree/demo/node-block.md',
      '/compiled_docs/tree/demo/render-child-nodes.en-us.md',
      '/compiled_docs/tree/demo/render-child-nodes.md',
      '/compiled_docs/tree/demo/search-tree.en-us.md',
      '/compiled_docs/tree/demo/search-tree.md',
    ],

    readme: [
      '/compiled_docs/tree/index.en-us.md',
      '/compiled_docs/tree/index.md',
    ],
  },
  'TreeSelect':  {
    demos: [
      '/compiled_docs/tree-select/demo/accessibility.en-us.md',
      '/compiled_docs/tree-select/demo/accessibility.md',
      '/compiled_docs/tree-select/demo/basic.en-us.md',
      '/compiled_docs/tree-select/demo/basic.md',
      '/compiled_docs/tree-select/demo/check.en-us.md',
      '/compiled_docs/tree-select/demo/check.md',
      '/compiled_docs/tree-select/demo/control.en-us.md',
      '/compiled_docs/tree-select/demo/control.md',
      '/compiled_docs/tree-select/demo/data.en-us.md',
      '/compiled_docs/tree-select/demo/data.md',
      '/compiled_docs/tree-select/demo/search.en-us.md',
      '/compiled_docs/tree-select/demo/search.md',
    ],

    readme: [
      '/compiled_docs/tree-select/index.en-us.md',
      '/compiled_docs/tree-select/index.md',
    ],
  },
  'Typography':  {
    demos: [
      '/compiled_docs/typography/demo/basic.en-us.md',
      '/compiled_docs/typography/demo/basic.md',
      '/compiled_docs/typography/demo/paragraph.en-us.md',
      '/compiled_docs/typography/demo/paragraph.md',
      '/compiled_docs/typography/demo/text.en-us.md',
      '/compiled_docs/typography/demo/text.md',
      '/compiled_docs/typography/demo/title.en-us.md',
      '/compiled_docs/typography/demo/title.md',
    ],

    readme: [
      '/compiled_docs/typography/index.en-us.md',
      '/compiled_docs/typography/index.md',
    ],
  },
  'Upload':  {
    demos: [
      '/compiled_docs/upload/demo/accessibility.en-us.md',
      '/compiled_docs/upload/demo/accessibility.md',
      '/compiled_docs/upload/demo/base.en-us.md',
      '/compiled_docs/upload/demo/base.md',
      '/compiled_docs/upload/demo/beforeupload.en-us.md',
      '/compiled_docs/upload/demo/beforeupload.md',
      '/compiled_docs/upload/demo/card.en-us.md',
      '/compiled_docs/upload/demo/card.md',
      '/compiled_docs/upload/demo/crop.en-us.md',
      '/compiled_docs/upload/demo/crop.md',
      '/compiled_docs/upload/demo/data.en-us.md',
      '/compiled_docs/upload/demo/data.md',
      '/compiled_docs/upload/demo/dragger.en-us.md',
      '/compiled_docs/upload/demo/dragger.md',
      '/compiled_docs/upload/demo/extra.en-us.md',
      '/compiled_docs/upload/demo/extra.md',
      '/compiled_docs/upload/demo/image.en-us.md',
      '/compiled_docs/upload/demo/image.md',
      '/compiled_docs/upload/demo/limit.en-us.md',
      '/compiled_docs/upload/demo/limit.md',
      '/compiled_docs/upload/demo/maxsize.en-us.md',
      '/compiled_docs/upload/demo/maxsize.md',
      '/compiled_docs/upload/demo/oss.en-us.md',
      '/compiled_docs/upload/demo/oss.md',
      '/compiled_docs/upload/demo/paste.en-us.md',
      '/compiled_docs/upload/demo/paste.md',
      '/compiled_docs/upload/demo/submit.en-us.md',
      '/compiled_docs/upload/demo/submit.md',
      '/compiled_docs/upload/demo/text.en-us.md',
      '/compiled_docs/upload/demo/text.md',
      '/compiled_docs/upload/demo/validation.en-us.md',
      '/compiled_docs/upload/demo/validation.md',
      '/compiled_docs/upload/demo/with-form.en-us.md',
      '/compiled_docs/upload/demo/with-form.md',
    ],

    readme: [
      '/compiled_docs/upload/index.en-us.md',
      '/compiled_docs/upload/index.md',
    ],
  },
  'VirtualList':  {
    demos: [
      '/compiled_docs/virtual-list/demo/basic.en-us.md',
      '/compiled_docs/virtual-list/demo/basic.md',
      '/compiled_docs/virtual-list/demo/initial-index.en-us.md',
      '/compiled_docs/virtual-list/demo/initial-index.md',
      '/compiled_docs/virtual-list/demo/item-size-getter.en-us.md',
      '/compiled_docs/virtual-list/demo/item-size-getter.md',
    ],

    readme: [
      '/compiled_docs/virtual-list/index.en-us.md',
      '/compiled_docs/virtual-list/index.md',
    ],
  },
};
