blank_issues_enabled: true
contact_links:
  - name: Create new issue
    url: https://fusion.design/feedback
    about: The issue which is not created via https://fusion.design/feedback will be closed immediately.
