"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var dayjs = require("dayjs");
var customParseFormat = require("dayjs/plugin/customParseFormat");
var updateLocale = require("dayjs/plugin/updateLocale");
var localeData = require("dayjs/plugin/localeData");
var quarterOfYear = require("dayjs/plugin/quarterOfYear");
var advancedFormat = require("dayjs/plugin/advancedFormat");
var weekOfYear = require("dayjs/plugin/weekOfYear");
require("dayjs/locale/zh-cn");
dayjs.extend(advancedFormat);
dayjs.extend(quarterOfYear);
dayjs.extend(customParseFormat);
dayjs.extend(updateLocale);
dayjs.extend(localeData);
dayjs.extend(weekOfYear);
dayjs.locale('zh-cn');
var datejs = dayjs;
datejs.isSelf = dayjs.isDayjs;
dayjs.localeData();
exports.default = datejs;
