declare const _default: {
    BACKSPACE: number;
    TAB: number;
    ENTER: number;
    SHIFT: number;
    CTRL: number;
    ALT: number;
    ESC: number;
    SPACE: number;
    END: number;
    HOME: number;
    LEFT: number;
    UP: number;
    RIGHT: number;
    DOWN: number;
    PAGE_UP: number;
    PAGE_DOWN: number;
    ESCAPE: number;
    LEFT_ARROW: number;
    UP_ARROW: number;
    RIGHT_ARROW: number;
    DOWN_ARROW: number;
    CONTROL: number;
    OPTION: number;
    CMD: number;
    COMMAND: number;
    DELETE: number;
};
export default _default;
