"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var text_1 = require("./text");
var paragraph_1 = require("./paragraph");
var typography_1 = require("./typography");
var title_1 = require("./title");
var WithSubTypography = typography_1.default;
WithSubTypography.Text = text_1.default;
WithSubTypography.Paragraph = paragraph_1.default;
WithSubTypography.H1 = (0, title_1.default)('h1');
WithSubTypography.H2 = (0, title_1.default)('h2');
WithSubTypography.H3 = (0, title_1.default)('h3');
WithSubTypography.H4 = (0, title_1.default)('h4');
WithSubTypography.H5 = (0, title_1.default)('h5');
WithSubTypography.H6 = (0, title_1.default)('h6');
exports.default = WithSubTypography;
