"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = require("tslib");
var component_1 = require("../util/component");
var menu_1 = tslib_1.__importDefault(require("../menu"));
var item_1 = tslib_1.__importDefault(require("./item"));
var group_1 = tslib_1.__importDefault(require("./group"));
var sub_nav_1 = tslib_1.__importDefault(require("./sub-nav"));
var popup_item_1 = tslib_1.__importDefault(require("./popup-item"));
var nav_1 = tslib_1.__importDefault(require("./nav"));
var Divider = menu_1.default.Divider;
var NavWithSubComponent = (0, component_1.assignSubComponent)(nav_1.default, { Item: item_1.default, Group: group_1.default, SubNav: sub_nav_1.default, PopupItem: popup_item_1.default, Divider: Divider });
exports.default = NavWithSubComponent;
